export const COURT_TYPES = [
  'Supreme Court',
  'High Court',
  'District Court',
  'Civil Court',
  'Criminal Court',
  'Family Court',
  'Consumer Court',
  'Labour Court',
  'Tax Court',
  'Tribunals',
  'Environmental Court',
  'Special Courts',
];

export const PRACTICE_AREAS = [
  'Criminal Law',
  'Civil Law',
  'Family Law',
  'Corporate Law',
  'Tax Law',
  'Cyber Law',
  'Labour Law',
  'Consumer Law',
  'Environmental Law',
  'Constitutional Law',
  'Administrative Law',
  'Arbitration',
  'Public Interest Litigation (PIL)',
  'Intellectual Property',
  'Real Estate Law',
  'Banking & Finance Law',
];

export const STATE_BAR_COUNCILS = [
  'Bar Council of Delhi',
  'Bar Council of Maharashtra & Goa',
  'Bar Council of Tamil Nadu & Puducherry',
  'Bar Council of Karnataka',
  'Bar Council of Kerala',
  'Bar Council of Gujarat',
  'Bar Council of Rajasthan',
  'Bar Council of Uttar Pradesh',
  'Bar Council of Madhya Pradesh',
  'Bar Council of West Bengal',
  'Bar Council of Andhra Pradesh',
  'Bar Council of Telangana',
  'Bar Council of Punjab & Haryana',
  'Bar Council of Bihar',
  'Bar Council of Odisha',
  'Bar Council of Jharkhand',
  'Bar Council of Chhattisgarh',
  'Bar Council of Himachal Pradesh',
  'Bar Council of Jammu & Kashmir',
  'Bar Council of North East',
  'Bar Council of Ladakh',
  'Bar Council of Sikkim',
  'Bar Council of Mizoram',
  'Bar Council of Nagaland',
  'Bar Council of Arunachal Pradesh',
  'Bar Council of Manipur',
  'Bar Council of Tripura',
  'Bar Council of Meghalaya',
  'Bar Council of Uttarakhand',
  
];

export const CASE_CATEGORIES = [
  'Criminal',
  'Civil',
  'Family',
  'Corporate',
  'Tax',
  'Cyber',
  'Labour',
  'Consumer',
  'Environmental',
  'Constitutional',
  'Administrative',
  'Arbitration',
  'Social Justice',
  'Human Rights',
  'Disability Law',
  'PIL',
  'Intellectual Property',
  'Real Estate',
  'Banking & Finance',
  'Tribal Law',
  'Rural Law',
  'Urban Law',
  'Transport Law',
  'Energy Law',
  'Water Law',
  'Air Law',
  'Space Law',
  'Cyber Law',
  'AI Law',
  'Blockchain Law',
  'Digital Law',
  'Data Law',
  'Data Protection Law',
  'Data Security Law',
  'Data Privacy Law',
  'Data Breach Law',
  'Data Leakage Law',

];

export const CASE_STATUSES = [
  { value: 'pending', label: 'Pending Review', color: 'bg-yellow-100 text-yellow-800' },
  { value: 'accepted', label: 'Accepted', color: 'bg-blue-100 text-blue-800' },
  { value: 'rejected', label: 'Rejected', color: 'bg-red-100 text-red-800' },
  { value: 'active', label: 'Active', color: 'bg-green-100 text-green-800' },
  { value: 'closed', label: 'Closed', color: 'bg-gray-100 text-gray-800' },
  { value: 'cancelled', label: 'Cancelled', color: 'bg-red-100 text-red-800' },
];

export const PRIORITY_LEVELS = [
  { value: 'low', label: 'Low', color: 'bg-gray-100 text-gray-800' },
  { value: 'medium', label: 'Medium', color: 'bg-blue-100 text-blue-800' },
  { value: 'high', label: 'High', color: 'bg-orange-100 text-orange-800' },
  { value: 'urgent', label: 'Urgent', color: 'bg-red-100 text-red-800' },
];

export const PAYMENT_STATUSES = [
  { value: 'unpaid', label: 'Unpaid', color: 'bg-red-100 text-red-800' },
  { value: 'partial', label: 'Partial', color: 'bg-yellow-100 text-yellow-800' },
  { value: 'paid', label: 'Paid', color: 'bg-green-100 text-green-800' },
];

export const MILESTONE_TYPES = [
  { value: 'accepted', label: 'Case Accepted', icon: 'CheckCircle' },
  { value: 'filed', label: 'Petition Filed', icon: 'FileText' },
  { value: 'hearing', label: 'Hearing Scheduled', icon: 'Calendar' },
  { value: 'evidence', label: 'Evidence Submitted', icon: 'FolderOpen' },
  { value: 'arguments', label: 'Final Arguments', icon: 'MessageSquare' },
  { value: 'closed', label: 'Case Closed', icon: 'XCircle' },
];
